### ISSUE TITLE
Large top margin

### ISSUE THREAD

**Issue by jaulz** [DerpyScripts/vue-bigheads#2]
Thanks for the port! Though, there seems to be large top margin:
![image](https://user-images.githubusercontent.com/5358638/111076574-1a66ea80-84ed-11eb-9435-d53341a9a934.png)

Any idea how that could be fixed?

**Comment by DerpyScripts** [comment]
Hi @jaulz, this extra spacing has been carried over from the original React library as certain hairstyles, hats, and accessories are able to extend both up and to the side, but nothing can extend downwards.
I probably wouldn't recommend cropping this in any way, as if you have multiple avatars side by side with different height hairstyles or hats, they would appear at different sizes or would align properly.

Here's an example screenshot of different height avatars from the original library's website:
![image](https://user-images.githubusercontent.com/21293197/111086850-6da16300-8516-11eb-8687-7fa7a0eedbdc.png)

**Comment by jaulz** [comment]
@DerpyScripts ah, thanks a lot 😊  So I will simply add a margin below so I can nicely align the circle with other elements.
